#!/usr/bin/env bash
# Script to print domain and subdomain information

print_domain_subdomain () {
    local domain="$1"
    local subdomain="$2"

    dig "$domain" +short ANY | awk -v sub="$subdomain" -v dom="$domain" '
    /^A/ {
        print "The subdomain " sub " is an A record and points to " $2
    }
    /^CNAME/ {
        print "The subdomain " sub " is a CNAME record and points to " $2
    }
    /^MX/ {
        print "The subdomain " sub " is an MX record and points to " $2
    }
    /^TXT/ {
        print "The subdomain " sub " is a TXT record and points to " $2
    }
    /^NS/ {
        print "The subdomain " sub " is an NS record and points to " $2
    }
    /^AAAA/ {
        print "The subdomain " sub " is an AAAA record and points to " $2
    }'
}

if [ "$#" -eq 2 ]; then
    # When domain and subdomain parameters are provided
    print_domain_subdomain "$2.$1" "$2"
else
    # When only domain is provided
    domain="$1"
    print_domain_subdomain "www.$domain" "www"
    print_domain_subdomain "lb-01.$domain" "lb-01"
    print_domain_subdomain "web-01.$domain" "web-01"
    print_domain_subdomain "web-02.$domain" "web-02"
fi

